name: Check Links
on: pull_request

jobs:
  Check-Website-Links:
    runs-on: ubuntu-18.04

    steps:
      - uses: CannonLock/test_links@master
        with:
          url_ignore: "/https://pacificresearchplatform.org//,/https://www.olcf.ornl.gov/summit//,/https://www.hpcwire.com/2019/11/22/51000-cloud-gpus-converge-to-power-neutrino-discovery-at-the-south-pole//,/https://docs.google.com/forms/d/1wUu3czRT_0Ask6rDW79QqrkQzyzR8ksyNM6uqWTOYXc//viewform/,/https://doi.org/10.1007/978-3-030-50743-5_2/,/https://pace.gatech.edu//,/https://www.amnh.org/research/computational-sciences/,/https://www.to.infn.it//,/https://www.amnh.org//,/https://doi.org/10.1007/s10822-013-9672-4/,/https://tbg.senckenberg.de//,/https://www.amnh.org/research/staff-directory/ariadna-morales/"
          file_ignore: "/./about/organization/index.html/"
